language: c
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - gfortran-8

      script:
        - cmake --version
        - ./install.sh --lang "C C++ Fortran" --build release --lib dynamic --mem heap --par none -s gnu

    - os: osx
      addons:
        homebrew:
          update: true
          packages:
            - gcc-9
            - cmake
            - openmpi
      before_install:
        - brew link gcc
        - brew link openmpi

      script:
        - cmake --version
        - ./install.sh --lang "C C++ Fortran" --build release --lib dynamic --mem heap --par none -s gnu
